# Generated by Django 6.0.2 on 2026-02-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationdistance',
            options={'ordering': ['from_destination', 'to_destination']},
        ),
    ]
