# Generated by Django 6.0.2 on 2026-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_add_destinationdistance_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='destinationdistance',
            constraint=models.CheckConstraint(condition=models.Q(('from_destination', models.F('to_destination')), _negated=True), name='no_self_referencing_distance'),
        ),
        migrations.AddConstraint(
            model_name='destinationimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('destination',), name='unique_primary_image_per_destination'),
        ),
    ]
